[package]
name = "krustens"
version = "1.0.0"
description = "A small application to generate json and yaml files of statistics based on Spotify streaming history files."
edition = "2021"
license = "MIT"
exclude = [
    ".vscode/*",
    "build.sh"
]
readme = "README.md"
homepage = "https://github.com/derrickp/krustens"
keywords = ["music"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = "3.1.12"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_yaml = "0.8.23"
